/*!
 * @lottie-animation-community/lottie-types - v1.2.0
 * Compiled Tue, 21 Jul 2026 13:34:54 UTC
 *
 * Generated by an automated process. DO NOT EDIT!
 *
 * Copyright 2022 Lottie Animation Community.
 *
 * Licensed under the MIT License,
 * You may obtain a copy of the License at:
 * https://github.com/lottie-animation-community/lottie-types/blob/main/LICENSE
 *
 * Type definitions for the Lottie animation format.
 * Definitions by: Aidos Sabit <https://github.com/aidosmf>.
 *
 * To report an issue with these types, please open a support ticket at:
 * https://github.com/lottie-animation-community/lottie-types/issues
 */
'use strict';

exports.BlendMode = void 0;
(function (BlendMode) {
    BlendMode.Normal = 0;
    BlendMode.Multiply = 1;
    BlendMode.Screen = 2;
    BlendMode.Overlay = 3;
    BlendMode.Darken = 4;
    BlendMode.Lighten = 5;
    BlendMode.ColorDodge = 6;
    BlendMode.ColorBurn = 7;
    BlendMode.HardLight = 8;
    BlendMode.SoftLight = 9;
    BlendMode.Difference = 10;
    BlendMode.Exclusion = 11;
    BlendMode.Hue = 12;
    BlendMode.Saturation = 13;
    BlendMode.Color = 14;
    BlendMode.Luminosity = 15;
    BlendMode.Add = 16;
    BlendMode.HardMix = 17;
    (function (VALUE) {
        VALUE[VALUE["NORMAL"] = 0] = "NORMAL";
        VALUE[VALUE["MULTIPLY"] = 1] = "MULTIPLY";
        VALUE[VALUE["SCREEN"] = 2] = "SCREEN";
        VALUE[VALUE["OVERLAY"] = 3] = "OVERLAY";
        VALUE[VALUE["DARKEN"] = 4] = "DARKEN";
        VALUE[VALUE["LIGHTEN"] = 5] = "LIGHTEN";
        VALUE[VALUE["COLOR_DODGE"] = 6] = "COLOR_DODGE";
        VALUE[VALUE["COLOR_BURN"] = 7] = "COLOR_BURN";
        VALUE[VALUE["HARD_LIGHT"] = 8] = "HARD_LIGHT";
        VALUE[VALUE["SOFT_LIGHT"] = 9] = "SOFT_LIGHT";
        VALUE[VALUE["DIFFERENCE"] = 10] = "DIFFERENCE";
        VALUE[VALUE["EXCLUSION"] = 11] = "EXCLUSION";
        VALUE[VALUE["HUE"] = 12] = "HUE";
        VALUE[VALUE["SATURATION"] = 13] = "SATURATION";
        VALUE[VALUE["COLOR"] = 14] = "COLOR";
        VALUE[VALUE["LUMINOSITY"] = 15] = "LUMINOSITY";
        VALUE[VALUE["ADD"] = 16] = "ADD";
        VALUE[VALUE["HARD_MIX"] = 17] = "HARD_MIX";
    })(BlendMode.VALUE || (BlendMode.VALUE = {}));
})(exports.BlendMode || (exports.BlendMode = {}));

exports.Composite = void 0;
(function (Composite) {
    Composite.Above = 1;
    Composite.Below = 2;
    (function (VALUE) {
        VALUE[VALUE["ABOVE"] = 1] = "ABOVE";
        VALUE[VALUE["BELOW"] = 2] = "BELOW";
    })(Composite.VALUE || (Composite.VALUE = {}));
})(exports.Composite || (exports.Composite = {}));

exports.EffectValueType = void 0;
(function (EffectValueType) {
    EffectValueType.Slider = 0;
    EffectValueType.Angle = 1;
    EffectValueType.Color = 2;
    EffectValueType.Point = 3;
    EffectValueType.Checkbox = 4;
    EffectValueType.Ignored = 6;
    EffectValueType.Dropdown = 7;
    EffectValueType.Layer = 10;
    (function (VALUE) {
        VALUE[VALUE["SLIDER"] = 0] = "SLIDER";
        VALUE[VALUE["ANGLE"] = 1] = "ANGLE";
        VALUE[VALUE["COLOR"] = 2] = "COLOR";
        VALUE[VALUE["POINT"] = 3] = "POINT";
        VALUE[VALUE["CHECKBOX"] = 4] = "CHECKBOX";
        VALUE[VALUE["IGNORED"] = 6] = "IGNORED";
        VALUE[VALUE["DROPDOWN"] = 7] = "DROPDOWN";
        VALUE[VALUE["LAYER"] = 10] = "LAYER";
    })(EffectValueType.VALUE || (EffectValueType.VALUE = {}));
})(exports.EffectValueType || (exports.EffectValueType = {}));

exports.EffectType = void 0;
(function (EffectType) {
    EffectType.Custom = 5;
    EffectType.PaintOverTransparent = 7;
    EffectType.Tint = 20;
    EffectType.Fill = 21;
    EffectType.Stroke = 22;
    EffectType.Tritone = 23;
    EffectType.ProLevels = 24;
    EffectType.DropShadow = 25;
    EffectType.RadialWipe = 26;
    EffectType.DisplacementMap = 27;
    EffectType.Matte3 = 28;
    EffectType.GaussianBlur = 29;
    EffectType.MeshWarp = 31;
    EffectType.Wavy = 32;
    EffectType.Spherize = 33;
    EffectType.Puppet = 34;
    (function (VALUE) {
        VALUE[VALUE["CUSTOM"] = 5] = "CUSTOM";
        VALUE[VALUE["PAINT_OVER_TRANSPARENT"] = 7] = "PAINT_OVER_TRANSPARENT";
        VALUE[VALUE["TINT"] = 20] = "TINT";
        VALUE[VALUE["FILL"] = 21] = "FILL";
        VALUE[VALUE["STROKE"] = 22] = "STROKE";
        VALUE[VALUE["TRITONE"] = 23] = "TRITONE";
        VALUE[VALUE["PRO_LEVELS"] = 24] = "PRO_LEVELS";
        VALUE[VALUE["DROP_SHADOW"] = 25] = "DROP_SHADOW";
        VALUE[VALUE["RADIAL_WIPE"] = 26] = "RADIAL_WIPE";
        VALUE[VALUE["DISPLACEMENT_MAP"] = 27] = "DISPLACEMENT_MAP";
        VALUE[VALUE["MATTE3"] = 28] = "MATTE3";
        VALUE[VALUE["GAUSSIAN_BLUR"] = 29] = "GAUSSIAN_BLUR";
        VALUE[VALUE["MESH_WARP"] = 31] = "MESH_WARP";
        VALUE[VALUE["WAVY"] = 32] = "WAVY";
        VALUE[VALUE["SPHERIZE"] = 33] = "SPHERIZE";
        VALUE[VALUE["PUPPET"] = 34] = "PUPPET";
    })(EffectType.VALUE || (EffectType.VALUE = {}));
})(exports.EffectType || (exports.EffectType = {}));

exports.FillRule = void 0;
(function (FillRule) {
    FillRule.NonZero = 1;
    FillRule.EvenOdd = 2;
    (function (VALUE) {
        VALUE[VALUE["NON_ZERO"] = 1] = "NON_ZERO";
        VALUE[VALUE["EVEN_ODD"] = 2] = "EVEN_ODD";
    })(FillRule.VALUE || (FillRule.VALUE = {}));
})(exports.FillRule || (exports.FillRule = {}));

exports.GradientType = void 0;
(function (GradientType) {
    GradientType.Linear = 1;
    GradientType.Radial = 2;
    (function (VALUE) {
        VALUE[VALUE["LINEAR"] = 1] = "LINEAR";
        VALUE[VALUE["RADIAL"] = 2] = "RADIAL";
    })(GradientType.VALUE || (GradientType.VALUE = {}));
})(exports.GradientType || (exports.GradientType = {}));

exports.LayerType = void 0;
(function (LayerType) {
    LayerType.Precomposition = 0;
    LayerType.SolidColor = 1;
    LayerType.Image = 2;
    LayerType.Null = 3;
    LayerType.Shape = 4;
    LayerType.Text = 5;
    LayerType.Audio = 6;
    LayerType.VideoPlaceholder = 7;
    LayerType.ImageSequence = 8;
    LayerType.Video = 9;
    LayerType.ImagePlaceholder = 10;
    LayerType.Guide = 11;
    LayerType.Adjustment = 12;
    LayerType.Camera = 13;
    LayerType.Light = 14;
    LayerType.Data = 15;
    (function (VALUE) {
        VALUE[VALUE["PRECOMPOSITION"] = 0] = "PRECOMPOSITION";
        VALUE[VALUE["SOLID_COLOR"] = 1] = "SOLID_COLOR";
        VALUE[VALUE["IMAGE"] = 2] = "IMAGE";
        VALUE[VALUE["NULL"] = 3] = "NULL";
        VALUE[VALUE["SHAPE"] = 4] = "SHAPE";
        VALUE[VALUE["TEXT"] = 5] = "TEXT";
        VALUE[VALUE["AUDIO"] = 6] = "AUDIO";
        VALUE[VALUE["VIDEO_PLACEHOLDER"] = 7] = "VIDEO_PLACEHOLDER";
        VALUE[VALUE["IMAGE_SEQUENCE"] = 8] = "IMAGE_SEQUENCE";
        VALUE[VALUE["VIDEO"] = 9] = "VIDEO";
        VALUE[VALUE["IMAGE_PLACEHOLDER"] = 10] = "IMAGE_PLACEHOLDER";
        VALUE[VALUE["GUIDE"] = 11] = "GUIDE";
        VALUE[VALUE["ADJUSTMENT"] = 12] = "ADJUSTMENT";
        VALUE[VALUE["CAMERA"] = 13] = "CAMERA";
        VALUE[VALUE["LIGHT"] = 14] = "LIGHT";
        VALUE[VALUE["DATA"] = 15] = "DATA";
    })(LayerType.VALUE || (LayerType.VALUE = {}));
})(exports.LayerType || (exports.LayerType = {}));

exports.LineCap = void 0;
(function (LineCap) {
    LineCap.Butt = 1;
    LineCap.Round = 2;
    LineCap.Square = 3;
    (function (VALUE) {
        VALUE[VALUE["BUTT"] = 1] = "BUTT";
        VALUE[VALUE["ROUND"] = 2] = "ROUND";
        VALUE[VALUE["SQUARE"] = 3] = "SQUARE";
    })(LineCap.VALUE || (LineCap.VALUE = {}));
})(exports.LineCap || (exports.LineCap = {}));

exports.LineJoin = void 0;
(function (LineJoin) {
    LineJoin.Miter = 1;
    LineJoin.Round = 2;
    LineJoin.Bevel = 3;
    (function (VALUE) {
        VALUE[VALUE["MITER"] = 1] = "MITER";
        VALUE[VALUE["ROUND"] = 2] = "ROUND";
        VALUE[VALUE["BEVEL"] = 3] = "BEVEL";
    })(LineJoin.VALUE || (LineJoin.VALUE = {}));
})(exports.LineJoin || (exports.LineJoin = {}));

exports.MaskMode = void 0;
(function (MaskMode) {
    MaskMode.No = "n";
    MaskMode.Add = "a";
    MaskMode.Subtract = "s";
    MaskMode.Intersect = "i";
    MaskMode.Lighten = "l";
    MaskMode.Darken = "d";
    MaskMode.Difference = "f";
    (function (VALUE) {
        VALUE["NO"] = "n";
        VALUE["ADD"] = "a";
        VALUE["SUBTRACT"] = "s";
        VALUE["INTERSECT"] = "i";
        VALUE["LIGHTEN"] = "l";
        VALUE["DARKEN"] = "d";
        VALUE["DIFFERENCE"] = "f";
    })(MaskMode.VALUE || (MaskMode.VALUE = {}));
})(exports.MaskMode || (exports.MaskMode = {}));

exports.MatteMode = void 0;
(function (MatteMode) {
    MatteMode.Normal = 0;
    MatteMode.Alpha = 1;
    MatteMode.InvertedAlpha = 2;
    MatteMode.Luma = 3;
    MatteMode.InvertedLuma = 4;
    (function (VALUE) {
        VALUE[VALUE["NORMAL"] = 0] = "NORMAL";
        VALUE[VALUE["ALPHA"] = 1] = "ALPHA";
        VALUE[VALUE["INVERTED_ALPHA"] = 2] = "INVERTED_ALPHA";
        VALUE[VALUE["LUMA"] = 3] = "LUMA";
        VALUE[VALUE["INVERTED_LUMA"] = 4] = "INVERTED_LUMA";
    })(MatteMode.VALUE || (MatteMode.VALUE = {}));
})(exports.MatteMode || (exports.MatteMode = {}));

exports.PolyStarType = void 0;
(function (PolyStarType) {
    PolyStarType.Star = 1;
    PolyStarType.Polygon = 2;
    (function (VALUE) {
        VALUE[VALUE["STAR"] = 1] = "STAR";
        VALUE[VALUE["POLYGON"] = 2] = "POLYGON";
    })(PolyStarType.VALUE || (PolyStarType.VALUE = {}));
})(exports.PolyStarType || (exports.PolyStarType = {}));

exports.ShapeDirection = void 0;
(function (ShapeDirection) {
    /**
     * Default Clockwise
     */
    ShapeDirection.Normal = 0;
    /**
     * Usually clockwise
     */
    ShapeDirection.Clockwise = 1;
    /**
     * Usually counter clockwise
     */
    ShapeDirection.ClockwiseReversed = 3;
    (function (VALUE) {
        VALUE[VALUE["NORMAL"] = 0] = "NORMAL";
        VALUE[VALUE["CLOCKWISE"] = 1] = "CLOCKWISE";
        VALUE[VALUE["CLOCKWISE_REVERSED"] = 3] = "CLOCKWISE_REVERSED";
    })(ShapeDirection.VALUE || (ShapeDirection.VALUE = {}));
})(exports.ShapeDirection || (exports.ShapeDirection = {}));

exports.ShapeType = void 0;
(function (ShapeType) {
    ShapeType.Rectangle = "rc";
    ShapeType.Ellipse = "el";
    ShapeType.PolygonStar = "sr";
    ShapeType.Path = "sh";
    ShapeType.Fill = "fl";
    ShapeType.Stroke = "st";
    ShapeType.GradientFill = "gf";
    ShapeType.GradientStroke = "gs";
    ShapeType.Group = "gr";
    ShapeType.Transform = "tr";
    ShapeType.RoundedCorners = "rd";
    ShapeType.PuckerBloat = "pb";
    ShapeType.Merge = "mm";
    ShapeType.Twist = "tw";
    ShapeType.OffsetPath = "op";
    ShapeType.ZigZag = "zz";
    ShapeType.Modifier = ""; // null
    ShapeType.Repeater = "rp";
    ShapeType.Trim = "tm";
    (function (VALUE) {
        VALUE["RECTANGLE"] = "rc";
        VALUE["ELLIPSE"] = "el";
        VALUE["POLYGON_STAR"] = "sr";
        VALUE["PATH"] = "sh";
        VALUE["FILL"] = "fl";
        VALUE["STROKE"] = "st";
        VALUE["GRADIENT_FILL"] = "gf";
        VALUE["GRADIENT_STROKE"] = "gs";
        VALUE["GROUP"] = "gr";
        VALUE["TRANSFORM"] = "tr";
        VALUE["ROUNDED_CORNERS"] = "rd";
        VALUE["PUCKER_BLOAT"] = "pb";
        VALUE["MERGE"] = "mm";
        VALUE["TWIST"] = "tw";
        VALUE["OFFSET_PATH"] = "op";
        VALUE["ZIG_ZAG"] = "zz";
        VALUE["MODIFIER"] = "";
        VALUE["REPEATER"] = "rp";
        VALUE["TRIM"] = "tm";
    })(ShapeType.VALUE || (ShapeType.VALUE = {}));
})(exports.ShapeType || (exports.ShapeType = {}));

exports.StrokeDashType = void 0;
(function (StrokeDashType) {
    StrokeDashType.Default = "d";
    StrokeDashType.Gap = "g";
    StrokeDashType.Offset = "o";
    (function (VALUE) {
        VALUE["DEFAULT"] = "d";
        VALUE["GAP"] = "g";
        VALUE["OFFSET"] = "o";
    })(StrokeDashType.VALUE || (StrokeDashType.VALUE = {}));
})(exports.StrokeDashType || (exports.StrokeDashType = {}));

exports.TextType = void 0;
(function (TextType) {
    let Based;
    (function (Based) {
        Based.Characters = 1;
        Based.CharacterExcludingSpaces = 2;
        Based.Words = 3;
        Based.Lines = 4;
    })(Based = TextType.Based || (TextType.Based = {}));
    (function (BASED) {
        BASED[BASED["CHARACTERS"] = 1] = "CHARACTERS";
        BASED[BASED["CHARACTER_EXCLUDING_SPACES"] = 2] = "CHARACTER_EXCLUDING_SPACES";
        BASED[BASED["WORDS"] = 3] = "WORDS";
        BASED[BASED["LINES"] = 4] = "LINES";
    })(TextType.BASED || (TextType.BASED = {}));
    let Caps;
    (function (Caps) {
        Caps.Regular = 0;
        Caps.AllCaps = 1;
        Caps.SmallCaps = 2;
    })(Caps = TextType.Caps || (TextType.Caps = {}));
    (function (TEXT_CAPS) {
        TEXT_CAPS[TEXT_CAPS["REGULAR"] = 0] = "REGULAR";
        TEXT_CAPS[TEXT_CAPS["ALL_CAPS"] = 1] = "ALL_CAPS";
        TEXT_CAPS[TEXT_CAPS["SMALL_CAPS"] = 2] = "SMALL_CAPS";
    })(TextType.TEXT_CAPS || (TextType.TEXT_CAPS = {}));
    let Grouping;
    (function (Grouping) {
        Grouping.Characters = 1;
        Grouping.Word = 2;
        Grouping.Line = 3;
        Grouping.All = 4;
    })(Grouping = TextType.Grouping || (TextType.Grouping = {}));
    (function (GROUPING) {
        GROUPING[GROUPING["CHARACTERS"] = 1] = "CHARACTERS";
        GROUPING[GROUPING["WORD"] = 2] = "WORD";
        GROUPING[GROUPING["LINE"] = 3] = "LINE";
        GROUPING[GROUPING["ALL"] = 4] = "ALL";
    })(TextType.GROUPING || (TextType.GROUPING = {}));
    let Justify;
    (function (Justify) {
        Justify.Left = 0;
        Justify.Right = 1;
        Justify.Center = 2;
        Justify.WithLastLineLeft = 3;
        Justify.WithLastLineRight = 4;
        Justify.WithLastLineCenter = 5;
        Justify.WithLastLineFull = 6;
    })(Justify = TextType.Justify || (TextType.Justify = {}));
    (function (JUSTIFY) {
        JUSTIFY[JUSTIFY["LEFT"] = 0] = "LEFT";
        JUSTIFY[JUSTIFY["RIGHT"] = 1] = "RIGHT";
        JUSTIFY[JUSTIFY["CENTER"] = 2] = "CENTER";
        JUSTIFY[JUSTIFY["WITH_LAST_LINE_LEFT"] = 3] = "WITH_LAST_LINE_LEFT";
        JUSTIFY[JUSTIFY["WITH_LAST_LINE_RIGHT"] = 4] = "WITH_LAST_LINE_RIGHT";
        JUSTIFY[JUSTIFY["WITH_LAST_LINE_CENTER"] = 5] = "WITH_LAST_LINE_CENTER";
        JUSTIFY[JUSTIFY["WITH_LAST_LINE_FULL"] = 6] = "WITH_LAST_LINE_FULL";
    })(TextType.JUSTIFY || (TextType.JUSTIFY = {}));
    let Shape;
    (function (Shape) {
        Shape.Square = 1;
        Shape.RampUp = 2;
        Shape.RampDown = 3;
        Shape.Triangle = 4;
        Shape.Round = 5;
        Shape.Smooth = 6;
    })(Shape = TextType.Shape || (TextType.Shape = {}));
    (function (SHAPE) {
        SHAPE[SHAPE["SQUARE"] = 1] = "SQUARE";
        SHAPE[SHAPE["RAMP_UP"] = 2] = "RAMP_UP";
        SHAPE[SHAPE["RAMP_DOWN"] = 3] = "RAMP_DOWN";
        SHAPE[SHAPE["TRIANGLE"] = 4] = "TRIANGLE";
        SHAPE[SHAPE["ROUND"] = 5] = "ROUND";
        SHAPE[SHAPE["SMOOTH"] = 6] = "SMOOTH";
    })(TextType.SHAPE || (TextType.SHAPE = {}));
    let FontPathOrigin;
    (function (FontPathOrigin) {
        FontPathOrigin.Local = 0;
        FontPathOrigin.CssUrl = 1;
        FontPathOrigin.ScriptUrl = 2;
        FontPathOrigin.FontUrl = 3;
    })(FontPathOrigin = TextType.FontPathOrigin || (TextType.FontPathOrigin = {}));
    (function (FONT_PATH_ORIGIN) {
        FONT_PATH_ORIGIN[FONT_PATH_ORIGIN["LOCAL"] = 0] = "LOCAL";
        FONT_PATH_ORIGIN[FONT_PATH_ORIGIN["CSS_URL"] = 1] = "CSS_URL";
        FONT_PATH_ORIGIN[FONT_PATH_ORIGIN["SCRIPT_URL"] = 2] = "SCRIPT_URL";
        FONT_PATH_ORIGIN[FONT_PATH_ORIGIN["FONT_URL"] = 3] = "FONT_URL";
    })(TextType.FONT_PATH_ORIGIN || (TextType.FONT_PATH_ORIGIN = {}));
    let VerticalJustify;
    (function (VerticalJustify) {
        VerticalJustify.Top = 0;
        VerticalJustify.Center = 1;
        VerticalJustify.Bottom = 2;
    })(VerticalJustify = TextType.VerticalJustify || (TextType.VerticalJustify = {}));
    (function (VERTICAL_JUSTIFY) {
        VERTICAL_JUSTIFY[VERTICAL_JUSTIFY["TOP"] = 0] = "TOP";
        VERTICAL_JUSTIFY[VERTICAL_JUSTIFY["CENTER"] = 1] = "CENTER";
        VERTICAL_JUSTIFY[VERTICAL_JUSTIFY["BOTTOM"] = 2] = "BOTTOM";
    })(TextType.VERTICAL_JUSTIFY || (TextType.VERTICAL_JUSTIFY = {}));
    let RangeSelectorMode;
    (function (RangeSelectorMode) {
        RangeSelectorMode.Add = 0;
        RangeSelectorMode.Subtract = 1;
        RangeSelectorMode.Intersect = 2;
        RangeSelectorMode.Min = 3;
        RangeSelectorMode.Max = 4;
        RangeSelectorMode.Difference = 5;
    })(RangeSelectorMode = TextType.RangeSelectorMode || (TextType.RangeSelectorMode = {}));
    (function (RANGE_SELECTOR_MODE) {
        RANGE_SELECTOR_MODE[RANGE_SELECTOR_MODE["ADD"] = 0] = "ADD";
        RANGE_SELECTOR_MODE[RANGE_SELECTOR_MODE["SUBTRACT"] = 1] = "SUBTRACT";
        RANGE_SELECTOR_MODE[RANGE_SELECTOR_MODE["INTERSECT"] = 2] = "INTERSECT";
        RANGE_SELECTOR_MODE[RANGE_SELECTOR_MODE["MIN"] = 3] = "MIN";
        RANGE_SELECTOR_MODE[RANGE_SELECTOR_MODE["MAX"] = 4] = "MAX";
        RANGE_SELECTOR_MODE[RANGE_SELECTOR_MODE["DIFFERENCE"] = 5] = "DIFFERENCE";
    })(TextType.RANGE_SELECTOR_MODE || (TextType.RANGE_SELECTOR_MODE = {}));
    /** @deprecated Use {@linkcode TextType.Based.Characters} or {@linkcode TextType.Grouping.Characters} */
    TextType.Characters = Based.Characters;
    /** @deprecated Use {@linkcode TextType.Based.CharacterExcludingSpaces} */
    TextType.CharacterExcludingSpaces = Based.CharacterExcludingSpaces;
    /** @deprecated Use {@linkcode TextType.Based.Words} */
    TextType.Words = Based.Words;
    /** @deprecated Use {@linkcode TextType.Based.Lines} */
    TextType.Lines = Based.Lines;
    /** @deprecated Use {@linkcode TextType.Caps.Regular} */
    TextType.Regular = Caps.Regular;
    /** @deprecated Use {@linkcode TextType.Caps.AllCaps} */
    TextType.AllCaps = Caps.AllCaps;
    /** @deprecated Use {@linkcode TextType.Caps.SmallCaps} */
    TextType.SmallCaps = Caps.SmallCaps;
    /** @deprecated Use {@linkcode TextType.Grouping.Word} */
    TextType.Word = Grouping.Word;
    /** @deprecated Use {@linkcode TextType.Grouping.Line} */
    TextType.Line = Grouping.Line;
    /** @deprecated Use {@linkcode TextType.Grouping.All} */
    TextType.All = Grouping.All;
    /** @deprecated Use {@linkcode TextType.Justify.Left} */
    TextType.Left = Justify.Left;
    /** @deprecated Use {@linkcode TextType.Justify.Right} */
    TextType.Right = Justify.Right;
    /** @deprecated Use {@linkcode TextType.Justify.Center} */
    TextType.Center = Justify.Center;
    /** @deprecated Use {@linkcode TextType.Justify.WithLastLineLeft} */
    TextType.WithLastLineLeft = Justify.WithLastLineLeft;
    /** @deprecated Use {@linkcode TextType.Justify.WithLastLineRight} */
    TextType.WithLastLineRight = Justify.WithLastLineRight;
    /** @deprecated Use {@linkcode TextType.Justify.WithLastLineCenter} */
    TextType.WithLastLineCenter = Justify.WithLastLineCenter;
    /** @deprecated Use {@linkcode TextType.Justify.WithLastLineFull} */
    TextType.WithLastLineFull = Justify.WithLastLineFull;
    /** @deprecated Use {@linkcode TextType.Shape.Square} */
    TextType.Square = Shape.Square;
    /** @deprecated Use {@linkcode TextType.Shape.RampUp} */
    TextType.RampUp = Shape.RampUp;
    /** @deprecated Use {@linkcode TextType.Shape.RampDown} */
    TextType.RampDown = Shape.RampDown;
    /** @deprecated Use {@linkcode TextType.Shape.Triangle} */
    TextType.Triangle = Shape.Triangle;
    /** @deprecated Use {@linkcode TextType.Shape.Round} */
    TextType.Round = Shape.Round;
    /** @deprecated Use {@linkcode TextType.Shape.Smooth} */
    TextType.Smooth = Shape.Smooth;
    /** @deprecated Use {@linkcode TextType.FontPathOrigin.Local} */
    TextType.Local = FontPathOrigin.Local;
    /** @deprecated Use {@linkcode TextType.FontPathOrigin.CssUrl} */
    TextType.CssUrl = FontPathOrigin.CssUrl;
    /** @deprecated Use {@linkcode TextType.FontPathOrigin.ScriptUrl} */
    TextType.ScriptUrl = FontPathOrigin.ScriptUrl;
    /** @deprecated Use {@linkcode TextType.FontPathOrigin.FontUrl} */
    TextType.FontUrl = FontPathOrigin.FontUrl;
    /** @deprecated Use {@linkcode TextType.VerticalJustify.Top} */
    TextType.VerticalJustifyTop = VerticalJustify.Top;
    /** @deprecated Use {@linkcode TextType.VerticalJustify.Center} */
    TextType.VerticalJustifyCenter = VerticalJustify.Center;
    /** @deprecated Use {@linkcode TextType.VerticalJustify.Bottom} */
    TextType.VerticalJustifyBottom = VerticalJustify.Bottom;
    /** @deprecated Use {@linkcode TextType.RangeSelectorMode.Add} */
    TextType.Add = RangeSelectorMode.Add;
    /** @deprecated Use {@linkcode TextType.RangeSelectorMode.Subtract} */
    TextType.Subtract = RangeSelectorMode.Subtract;
    /** @deprecated Use {@linkcode TextType.RangeSelectorMode.Intersect} */
    TextType.Intersect = RangeSelectorMode.Intersect;
    /** @deprecated Use {@linkcode TextType.RangeSelectorMode.Min} */
    TextType.Min = RangeSelectorMode.Min;
    /** @deprecated Use {@linkcode TextType.RangeSelectorMode.Max} */
    TextType.Max = RangeSelectorMode.Max;
    /** @deprecated Use {@linkcode TextType.RangeSelectorMode.Difference} */
    TextType.Difference = RangeSelectorMode.Difference;
})(exports.TextType || (exports.TextType = {}));

exports.TrimMultipleShapes = void 0;
(function (TrimMultipleShapes) {
    TrimMultipleShapes.Individually = 1;
    TrimMultipleShapes.Simultaneously = 2;
    (function (VALUES) {
        VALUES[VALUES["INDIVIDUALLY"] = 1] = "INDIVIDUALLY";
        VALUES[VALUES["SIMULTANEOUSLY"] = 2] = "SIMULTANEOUSLY";
    })(TrimMultipleShapes.VALUES || (TrimMultipleShapes.VALUES = {}));
})(exports.TrimMultipleShapes || (exports.TrimMultipleShapes = {}));

exports.LayerStyleType = void 0;
(function (LayerStyleType) {
    LayerStyleType.Stroke = 0;
    LayerStyleType.DropShadow = 1;
    LayerStyleType.InnerShadow = 2;
    LayerStyleType.OuterGlow = 3;
    LayerStyleType.InnerGlow = 4;
    LayerStyleType.BevelEmboss = 5;
    LayerStyleType.Satin = 6;
    LayerStyleType.ColorOverlay = 7;
    LayerStyleType.GradientOverlay = 8;
})(exports.LayerStyleType || (exports.LayerStyleType = {}));
//# sourceMappingURL=index.cjs.map
