import dts from "rollup-plugin-dts";
import typescript from "@rollup/plugin-typescript";
import pkg from "./package.json" with { type: "json" };

const compiledAt = new Date().toUTCString().replace(/GMT/g, "UTC");

const banner = [
  `/*!`,
  ` * ${pkg.name} - v${pkg.version}`,
  ` * Compiled ${compiledAt}`,
  ` *`,
  ` * Generated by an automated process. DO NOT EDIT!`,
  ` *`,
  ` * Copyright 2022 Lottie Animation Community.`,
  ` *`,
  ` * Licensed under the MIT License,`,
  ` * You may obtain a copy of the License at:`,
  ` * https://github.com/lottie-animation-community/lottie-types/blob/main/LICENSE`,
  ` *`,
  ` * Type definitions for the Lottie animation format.`,
  ` * Definitions by: Aidos Sabit <https://github.com/aidosmf>.`,
  ` *`,
  ` * To report an issue with these types, please open a support ticket at:`,
  ` * https://github.com/lottie-animation-community/lottie-types/issues`,
  ` */`,
].join("\n");

const config = [
  {
    input: "./src/index.ts",
    output: [
      {
        banner,
        file: "./index.js",
        format: "es",
        sourcemap: true,
      },
    ],
    plugins: [typescript({ tsconfig: "./tsconfig.json" })],
  },
  {
    input: "./src/index.ts",
    output: [{ banner, file: "./index.d.ts", format: "es" }],
    plugins: [dts()],
  },
];

export default config;
